use crate::config::Key;

/// Maps a keycode to a platform-agnostic Key.
/// This function handles both special keys and character keys with shift modification.
/// Used by both X11 and Wayland backends.
pub fn keycode_to_key(kc: u32, shift_held: bool) -> Option<Key> {
    // Special (non-character) keys — checked first, unaffected by shift
    match kc {
        1 => return Some(Key::Escape),
        14 => return Some(Key::Backspace),
        15 => return Some(Key::Tab),
        28 => return Some(Key::Enter),
        57 => return Some(Key::Space),
        // Navigation
        102 => return Some(Key::Home),
        103 => return Some(Key::End),
        104 => return Some(Key::Up),
        105 => return Some(Key::Left),
        106 => return Some(Key::Right),
        107 => return Some(Key::PageUp),
        108 => return Some(Key::PageDown),
        109 => return Some(Key::Down),
        110 => return Some(Key::Insert),
        111 => return Some(Key::Delete),
        // Function keys
        59 => return Some(Key::F1),
        60 => return Some(Key::F2),
        61 => return Some(Key::F3),
        62 => return Some(Key::F4),
        63 => return Some(Key::F5),
        64 => return Some(Key::F6),
        65 => return Some(Key::F7),
        66 => return Some(Key::F8),
        67 => return Some(Key::F9),
        68 => return Some(Key::F10),
        87 => return Some(Key::F11),
        88 => return Some(Key::F12),
        // Lock / toggle
        58 => return Some(Key::CapsLock),
        69 => return Some(Key::NumLock),
        70 => return Some(Key::ScrollLock),
        // System
        99 => return Some(Key::PrintScreen),
        119 => return Some(Key::Pause),
        127 => return Some(Key::ContextMenu),
        // Modifiers
        125 => return Some(Key::MetaLeft),
        126 => return Some(Key::MetaRight),
        29 => return Some(Key::ControlLeft),
        97 => return Some(Key::ControlRight),
        56 => return Some(Key::AltLeft),
        100 => return Some(Key::AltRight),
        42 => return Some(Key::ShiftLeft),
        50 => return Some(Key::ShiftLeft),
        54 => return Some(Key::ShiftRight),
        143 => return Some(Key::Fn),
        // Numpad
        82 => return Some(Key::NumPad0),
        79 => return Some(Key::NumPad1),
        80 => return Some(Key::NumPad2),
        81 => return Some(Key::NumPad3),
        75 => return Some(Key::NumPad4),
        76 => return Some(Key::NumPad5),
        77 => return Some(Key::NumPad6),
        71 => return Some(Key::NumPad7),
        72 => return Some(Key::NumPad8),
        73 => return Some(Key::NumPad9),
        78 => return Some(Key::NumPadAdd),
        74 => return Some(Key::NumPadSubtract),
        55 => return Some(Key::NumPadMultiply),
        98 => return Some(Key::NumPadDivide),
        83 => return Some(Key::NumPadDecimal),
        96 => return Some(Key::NumPadEnter),
        _ => {}
    }

    // Character keys — shift changes the produced character
    let ch = if shift_held {
        match kc {
            // Shifted digits → symbols
            2 => '!',
            3 => '@',
            4 => '#',
            5 => '$',
            6 => '%',
            7 => '^',
            8 => '&',
            9 => '*',
            10 => '(',
            11 => ')',
            // Shifted punctuation
            12 => '_',
            13 => '+',
            26 => '{',
            27 => '}',
            43 => '|',
            39 => ':',
            40 => '"',
            51 => '<',
            52 => '>',
            53 => '?',
            41 => '~',
            // Shifted letters → uppercase
            16 => 'Q',
            17 => 'W',
            18 => 'E',
            19 => 'R',
            20 => 'T',
            21 => 'Y',
            22 => 'U',
            23 => 'I',
            24 => 'O',
            25 => 'P',
            30 => 'A',
            31 => 'S',
            32 => 'D',
            33 => 'F',
            34 => 'G',
            35 => 'H',
            36 => 'J',
            37 => 'K',
            38 => 'L',
            44 => 'Z',
            45 => 'X',
            46 => 'C',
            47 => 'V',
            48 => 'B',
            49 => 'N',
            50 => 'M',
            _ => return None,
        }
    } else {
        match kc {
            // Digits
            2 => '1',
            3 => '2',
            4 => '3',
            5 => '4',
            6 => '5',
            7 => '6',
            8 => '7',
            9 => '8',
            10 => '9',
            11 => '0',
            // Punctuation
            12 => '-',
            13 => '=',
            26 => '[',
            27 => ']',
            43 => '\\',
            39 => ';',
            40 => '\'',
            51 => ',',
            52 => '.',
            53 => '/',
            41 => '`',
            // Letters
            16 => 'q',
            17 => 'w',
            18 => 'e',
            19 => 'r',
            20 => 't',
            21 => 'y',
            22 => 'u',
            23 => 'i',
            24 => 'o',
            25 => 'p',
            30 => 'a',
            31 => 's',
            32 => 'd',
            33 => 'f',
            34 => 'g',
            35 => 'h',
            36 => 'j',
            37 => 'k',
            38 => 'l',
            44 => 'z',
            45 => 'x',
            46 => 'c',
            47 => 'v',
            48 => 'b',
            49 => 'n',
            50 => 'm',
            _ => return None,
        }
    };
    Some(Key::Char(ch))
}